### ISSUE TITLE
Get access for data to run script for team

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/archetypes-intervention-impact#286]
There is data required to run the scripts in Dropbox. We need to obtain access before project starts

**Comment by SLiu-IDM** [comment]
@shchen-idmod, @ZDu-IDM, @devclinton, @jonathanhhb, @tfischle-idmod  - can you verify if you have access to this, using IDM dropbox credentials? https://www.dropbox.com/sh/ep3jsdkqe1gif34/AABUha1q2YZ4nWTi7aQRSpcza?dl=0

**Comment by ZDu-IDM** [comment]
@SLiu-IDM No, I can't!

**Comment by tfischle-idmod** [comment]
@SLiu-IDM  Me neither. Tried idmod email and BMGF email.

**Comment by SLiu-IDM** [comment]
@ZDu-IDM  & @tfischle-idmod  - have you accessed IDM Dropbox before? If not, I can follow up with IT to set up your accounts (note: dropbox access still using IDM email addresses).

**Comment by ZDu-IDM** [comment]
@SLiu-IDM Yes, I used to login to access Prashanth's data.

**Comment by SLiu-IDM** [comment]
@ZDu-IDM Caitlin added you, please confirm access.

**Comment by ZDu-IDM** [comment]
@SLiu-IDM  This is the  screen I got after fill up with my e-mail: zdu@idmod.org

![image](https://user-images.githubusercontent.com/19961398/148108326-d214be35-528a-4525-9ab3-2eee66143f81.png)

**Comment by shchen-idmod** [comment]
I got same error as Zhaowei.

**Comment by SLiu-IDM** [comment]
Adding note here for others: Sharon & Zhaowei were able to access using idmod accounts. 
So, we're all set from a permissions standpoint.

**Comment by jonathanhhb** [comment]
I was able to get in after trying a different browser. The whole cached creds thing is a bit of a nightmare, but I've gotten used to finding workarounds...

**Comment by shchen-idmod** [comment]
Link to ticketoff ticket in emodpy-malaria which contains what branch we should work on:
https://github.com/InstituteforDiseaseModeling/emodpy-malaria/issues/326

**Comment by shchen-idmod** [comment]
Original pip list:
https://github.com/InstituteforDiseaseModeling/emodpy-malaria/issues/380

**Comment by shchen-idmod** [comment]
Original burnin in COMPS:
https://comps.idmod.org/#explore/Simulations?filters=ExperimentId=8582e124-75b2-eb11-a2e3-c4346bcb7275&offset=0&count=80
