### ISSUE TITLE
Determine how we generate interventions from data file

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/archetypes-intervention-impact#290]
The workflow being used has interventions generated from data file. We will need some utility function that takes that file as input and generates the correct interventions. Ideally it will be reusable for other projects

Some open questions
* Should this live in emodpy-malaria?
* What structure should we make the file
* How do we make it flexible

**Comment by jonathanhhb** [comment]
_Should this live in emodpy-malaria?_
Yes, I think so. These are all malaria-specific.
    
    _What structure should we make the file?_
Not sure exactly what you mean here, but I think we want to accept her csv files as inputs and do all the python to ingest those, and use emodpy-malaria.interventions functions to turn them into a campaign.json.

    _How do we make it flexible_
Iteratively? I think we should always maintain the goal that Amelia, or the future end user, can do all their work from the datafile without worrying about or editing the Python.

**Comment by SLiu-IDM** [comment]
This work gets done w/ InstituteforDiseaseModeling/archetypes-intervention-impact-idmtools#5
