### ISSUE TITLE
Verify all interventions and configuration options available

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/archetypes-intervention-impact#292]
Interventions need to be verified they exist and support the options required. We should look at data file to validate what interventions are actually being used.

**Comment by jonathanhhb** [comment]
My info might be old and maybe I should just look at the actual input file :) but from my recollection we're talking about ITNs, IRS, and Drugs, and relying on coverage, efficacy, and distribution times.

**Comment by stitova-idm** [comment]
I checked over interventions_functions.py:

Interventions we don't have implemented or don't have full functionality implemented: 
1. configure_adherent_drug - not implemented <---- this isn't an intervention in of itself and the user can just create a dictionary to pass in, but (I think) this would make it easier to use adherent drug. 
2. add_larvicide_wrapper uses add_larvicides - not implemented 
3. add_ITN_age_season - not implemented, but can be recreated with emodpy-malaria\interventions\udbednet.py (usage-dependent bednet): Amelia does not use the age/season parameters, so regular itn intervention will work just fine. 
4. add_irs_group - uses add_IRS with trigger conditions, we do not currently have that functionality in emodpy-malaria\interventions\irs.py, it is scheduled only.

Others that we already have implemented:
add_health_seeking_by_coverage/add_health_seeking - implmemented as add_treatment_seeking in emodpy-malaria\interventions\treatment_seeking.py 
add_health_seeking_by_coverage/add_health_seeking - implmemented as add_treatment_seeking in emodpy-malaria\interventions\treatment_seeking.py 
add_atsb - implmented as SugarTrap in emodpy-malaria\interventions\sugartrap.py
add_ors/add_ors_node - implemented as SpaceSpraying in emodpy-malaria\interventions\spacespraying.py
add_ivermectin_wrapper/add_ivermectin - implemented as Ivermectin in emodpy-malaria\interventions\ivermectin
add_diagnostic_survey - implemented as add_diagnostic_survey in emodpy-malaria\interventions\diag_survey.py

**Comment by SLiu-IDM** [comment]
@jonathanhhb - could you review & create issues for the missing interventions?

**Comment by jonathanhhb** [comment]
@stitova-idm Thanks for the research and the concise and precise information. Very helpful.

**Comment by jonathanhhb** [comment]
@stitova-idm 

Regarding number 3, add_ITN_age_season, I'm only seeing 1 case of her calling this function, and it looks like this:
```
            add_ITN_age_season(cb,
                               **coverage_all**=per_round_coverage,
                               **discard**={"halflife": discard_halflife},
                               **start**=(365 * year) + (30 * this_round) + start_day,
                               **ind_property_restrictions**=IP)
```

So while she calls the age_season function, I'm not seeing any use of the age or season configurability params, or actually any of the other efficacy configs.

**Comment by stitova-idm** [comment]
@jonathanhhb  - you are correct. There is no application of the age or season configurability parameters. I'll update my notes above.

**Comment by SLiu-IDM** [comment]
Linking issues for specific work
#305 , #306 , #307

**Comment by SLiu-IDM** [comment]
@stitova-idm : do you mind having a look at this again using this branch, to see if there's anything we missed? https://github.com/bertozzivill/archetypes-intervention-impact/tree/add-itn-options

**Comment by stitova-idm** [comment]
Update: Looks very similar

1) but add_ITN_age_season is using age dependency this time:
![image](https://user-images.githubusercontent.com/16845361/152266662-55b8b14f-28f2-480f-833a-5b16eba190e0.png)

everything else holds up.
