### ISSUE TITLE
Verify reporters used are available

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/archetypes-intervention-impact#293]
Verify EMOD reporters used are available and support all options

**Comment by stitova-idm** [comment]
All the reporters that exist for EMOD in Malaira-Ongoing are in emodpy-malaria in emodpy_malaria\reporters. The examples for most are in examples\add_reports

**Comment by stitova-idm** [comment]
There is probably some syntax and parameter changes from Amelia's reporters because time
