### ISSUE TITLE
Discuss Demographics generator

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/archetypes-intervention-impact#296]
Discuss Demographics generator. It is used by Amelia and NU. It is somewhat complex so @jonathanhhb  would prefer if we can maybe make it a bit more generic. If not, we need to port and decide is it EMODPy or emod-api

**Comment by jonathanhhb** [comment]
It looks to me as though we can get where we need to go without worrying about DemographicsGenerator.
