### ISSUE TITLE
Verify multi-core features work

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/archetypes-intervention-impact#297]
Test that multi-core works in idmtools
Test that multi-core data aggregation works(burn-in with multi-core, transition to single core)

**Comment by shchen-idmod** [comment]
Verified 1: run burnin and intervention with same number of multi-cores. It works.
https://comps.idmod.org/#explore/Experiments?filters=Id=bc8fb961-f2c0-ec11-a9f6-9440c9be2c51&offset=0&count=80&selectedId=bc8fb961-f2c0-ec11-a9f6-9440c9be2c51
https://comps.idmod.org/#explore/Experiments?filters=Id=bc8fb961-f2c0-ec11-a9f6-9440c9be2c51&offset=0&count=80&selectedId=bc8fb961-f2c0-ec11-a9f6-9440c9be2c51

**Comment by shchen-idmod** [comment]
Verified 2: if burnin with 2 cores, intervention can not use single core. https://comps.idmod.org/#explore/Simulations?filters=Id=2c52ac2c-f3c0-ec11-a9f6-9440c9be2c51&offset=0&count=80&selectedId=2c52ac2c-f3c0-ec11-a9f6-9440c9be2c51
So if use multi-core, burnin and intervention need to be the same multi-cores

**Comment by SLiu-IDM** [comment]
Thanks @shchen-idmod ! fyi @bertozzivill
