### ISSUE TITLE
Translate generate demographics.py

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/archetypes-intervention-impact#300]
https://github.com/InstituteforDiseaseModeling/archetypes-intervention-impact/blob/master/intervention_impact/run_simulations/01_generate_demographics.py to new repo. This will involve some new configuration possibly.

**Comment by SLiu-IDM** [comment]
https://github.com/InstituteforDiseaseModeling/archetypes-intervention-impact-idmtools/pull/7
