### ISSUE TITLE
Transfer simulation_functions.py to the new repo

### ISSUE THREAD

**Issue by devclinton** [InstituteforDiseaseModeling/archetypes-intervention-impact#303]
https://github.com/InstituteforDiseaseModeling/archetypes-intervention-impact/blob/master/intervention_impact/run_simulations/simulation_functions.py

**Comment by SLiu-IDM** [comment]
https://github.com/InstituteforDiseaseModeling/archetypes-intervention-impact-idmtools/pull/13
