### ISSUE TITLE
Extend emodpy-malaria to include configure_adherent_drug function(ality)

### ISSUE THREAD

**Issue by jonathanhhb** [InstituteforDiseaseModeling/archetypes-intervention-impact#305]
See example usage in this repo here:

https://github.com/InstituteforDiseaseModeling/archetypes-intervention-impact/blob/e7be7be6a689d15da4a8eb658cf80d65a65cbf19/intervention_impact/run_simulations/intervention_functions.py#L303

Need to add link to actual legacy code in dtk-tools "malaria" package.

**Comment by jonathanhhb** [comment]
https://github.com/InstituteforDiseaseModeling/dtk-tools-malaria/blob/4237e33d4ff3e442280f59163ccbf2301b73f099/malaria/interventions/adherent_drug.py#L6

**Comment by jonathanhhb** [comment]
This is relatively straightforward and short except I really don't want the user to have to pass through correctly configured WaningConfig json blobs. That goes 100% against the whole point of emod-api/py*. 

We can either find a more human-facing way of capturing the key configuration points, or maybe find out what the actual sublist of waning profiles people would actually use here and build the design around that.

**Comment by jonathanhhb** [comment]
Having a hard time getting my head fully around all the details of AdherentDrug! :( Hopefully I don't have to. My hunch/hope is that we can assume the user is going to go with MapCount and just provide the Times and Values arrays in the python interface.

**Comment by jonathanhhb** [comment]
Turns out this isn't needed for Amelia's work.

**Comment by SLiu-IDM** [comment]
Svetlana has PR here: https://github.com/InstituteforDiseaseModeling/emodpy-malaria/pull/413
