### ISSUE TITLE
Extend emodpy-malaria with add_larvicide function(ality)

### ISSUE THREAD

**Issue by jonathanhhb** [InstituteforDiseaseModeling/archetypes-intervention-impact#306]
Pretty trivial. Existing code looks like this:

```
def add_larvicide_wrapper(cb, coverage, start_days=[0], kill_duration=100):

    for start_day in start_days:
        add_larvicides(cb, start_day=start_day,
                     coverage=coverage,
                     killing_duration=kill_duration)

    return {"Larvicide_Coverage": coverage, "Larvicide_Start": start_days[0], "Larvicide_Kill_Halflife": kill_duration}
```

Might want a better name than "wrapper". And a doc string. We may have other "coverage by time" intervention wrappers and there may be a chance to standardize this approach.

**Comment by jonathanhhb** [comment]
Oh, apparently we don't have an add_larvicide intervention function yet. :(

**Comment by ckirkman-IDM** [comment]
No wrapper is needed as part of this issue, the wrapping of the to-be-ported add_larvicides() function into emodpy-malaria from dtk-tools/dtk-tools-malaria (wherever) is already in scope for issue:
https://github.com/InstituteforDiseaseModeling/archetypes-intervention-impact-idmtools/issues/6

Please update the title of the task as I have no permissions to do so.

**Comment by ckirkman-IDM** [comment]
Issue moved to [InstituteforDiseaseModeling/emodpy-malaria #411](https://github.com/InstituteforDiseaseModeling/emodpy-malaria/issues/411) via [**ZenHub**](https://www.zenhub.com/)
